### ISSUE TITLE
Serenity reports show tab name as **Epi Cs**  instead **Epics**

### ISSUE THREAD

**Issue by r2d2-github** [serenity-bdd/serenity-cucumber-starter#124]
Serenity version 4.x.x onwards
Issue: Reports show tab name as **Epi Cs**  instead **Epics**
I am using following property in serenity - **serenity.requirement.types=EPIC**
Image to refer:
<img width="463" alt="image" src="https://github.com/serenity-bdd/serenity-cucumber-starter/assets/25445287/85bb75b8-076e-477a-9ee8-097aa3f66675">

**Comment by wakaleo** [comment]
Try with:

serenity.requirement.types=epic

**Comment by r2d2-github** [comment]
It worked. Thank you so much for your help.
<img width="568" alt="image" src="https://github.com/serenity-bdd/serenity-cucumber-starter/assets/25445287/cf18c6ab-0bab-4433-b23c-39810989aeee">
