### ISSUE TITLE
When execution is done using '-Dcucumber.filter.tags' then Feature files which are not part of execution also comes on the reports dashboard

### ISSUE THREAD

**Issue by gorakshasabnis** [serenity-bdd/serenity-cucumber-starter#142]
Hi,

I have around 18+ features in my project of serenity BDD with cucumber but when I execute automation using '-Dcucumber.filter.tags=@Dashboard and @Settings'' i.e. using tags then feature files which are not part of the execution also comes in the dashboard graph.  (Please find sceenshot at the bottom)

Also, serenity.logging is verbose or normal then in console also it lists all the feature names instead of listing features which are part of the execution.

Is there a way to omit features files which are not part of execution from the report ?  

My concern is once feature list reaches to 100 or something and if 30/40 feature files are not part of some execution then that will leave a huge empty space in the serenity report's dashboard. Kindly help.

`net.serenity-bdd version 4.1.6`

<img width="1746" alt="image" src="https://github.com/serenity-bdd/serenity-cucumber-starter/assets/18349033/37e7664b-c173-4d55-a579-5cd51a8b177e">

**Comment by wakaleo** [comment]
Use -Dtags for Cucumber 7 and JUnit 5 - see https://serenity-bdd.github.io/docs/reporting/filtering_reports

**Comment by gorakshasabnis** [comment]
Thanks john. When i used -Dtags='Dashboard' then it executed only dashboard cases and showed only dashboard specific feature files in the execution report. 
However, it doesn't execute any cases when -Dtags='Dashboard and Sanity' is used; even though @Sanity tag is present in the feature. It works fine with old command line argument -Dcucumber.filter.tags="@Dashboard and @Sanity". Kindly help.
