### ISSUE TITLE
Not able to run script in amazon Linux 2  instance

### ISSUE THREAD

**Issue by Abhishekk099** [serenity-bdd/serenity-cucumber-starter#145]
I was able to trigger test initially, few days back but suddenly from y-day am getting below on 'mvn clean verify' ,I tried with this stater project as well getting the same issue.
 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project cucumber-starter: Compilation failure
[ERROR] /home/ec2-user/serenity/serenity-cucumber-starter/src/test/java/starter/search/SearchForm.java:[3,42] cannot access net.serenitybdd.screenplay.targets.Target
[ERROR]   bad class file: /home/ec2-user/.m2/repository/net/serenity-bdd/serenity-screenplay-webdriver/4.1.12/serenity-screenplay-webdriver-4.1.12.jar(net/serenitybdd/screenplay/targets/Target.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by wakaleo** [comment]
You are trying to run Serenity with Java 8, you need Java 11 or higher.

**Comment by Abhishekk099** [comment]
Thanks for the reply , i was able to reproduce in my local using older java version will ask devops team  to update java version and try again .
