### ISSUE TITLE
StepDefinitions

### ISSUE THREAD

**Issue by York6666** [serenity-bdd/serenity-cucumber-starter#16]
Hello everyone, I have a question.
Download and run the project with the command mvn clean verify and the report appears very well. What caught my attention was that in the feature in the step definitions, even though they are already created, they are still shaded yellow and it appears as if I had not created them.

![image](https://user-images.githubusercontent.com/48634709/77705053-a904f380-6f8c-11ea-9c7a-bedfd70b6b0c.png)

but the step definitions are already created
![image](https://user-images.githubusercontent.com/48634709/77705081-be7a1d80-6f8c-11ea-98cb-1f0875c193b6.png)

and even if I recreate the step definitions, they continue with the yellow shadow showing that they have not been created.

I have not made any modification to the pom.
thanks.

**Comment by edricklacbayo** [comment]
If you're using Java, What I used to do is, Download Cucucmber for Java Plugin from IntelliJ Plugins. 
File > Settings > Plugins 
![image](https://user-images.githubusercontent.com/28752767/78103992-e18b4e00-7420-11ea-832b-73092341d5bf.png)
It works for me, I hope on yours too.

**Comment by York6666** [comment]
> If you're using Java, What I used to do is, Download Cucucmber for Java Plugin from IntelliJ Plugins.
> File > Settings > Plugins
> ![image](https://user-images.githubusercontent.com/28752767/78103992-e18b4e00-7420-11ea-832b-73092341d5bf.png)
> It works for me, I hope on yours too.

hello but i already have the plugin

**Comment by wakaleo** [comment]
This is related to the IntelliJ Cucumber plugin - make sure you have the latest version of IntelliJ

**Comment by York6666** [comment]
> This is related to the IntelliJ Cucumber plugin - make sure you have the latest version of IntelliJ

Hello I am working with intellij 2019 2.4 and currently I have other serenity projects with cucumber and it creates the steps for me without problems. But with this version "serenity-cucumber-starter" even though I create the steps well, the gherkin is still shaded yellow.

I create the steps definitions
![1](https://user-images.githubusercontent.com/48634709/78309738-766d7480-7511-11ea-819e-62d8089a3cf1.png)

![2](https://user-images.githubusercontent.com/48634709/78309764-871dea80-7511-11ea-84c9-829436125e04.png)

These are the steps definitions created
![3](https://user-images.githubusercontent.com/48634709/78309800-a1f05f00-7511-11ea-9016-669c434be34b.png)

And the gherkin is still the same color
![4](https://user-images.githubusercontent.com/48634709/78309810-a9176d00-7511-11ea-8b84-ca0642183fd1.png)

**Comment by wakaleo** [comment]
You need a version of IntelliJ that supports Cucumber 5. Try with IntelliJ 2019.3.3
or higher

**Comment by York6666** [comment]
> You need a version of IntelliJ that supports Cucumber 5. Try with IntelliJ 2019.3.3
> or higher
you were right. Upgrade to the latest version intellij and it worked. Thank you very much

![image](https://user-images.githubusercontent.com/48634709/79023291-8acef400-7b45-11ea-958f-2977be372812.png)

![image](https://user-images.githubusercontent.com/48634709/79023273-7ab71480-7b45-11ea-978c-be7a41bbbedf.png)
