### ISSUE TITLE
Cucumber Expressions doesn't work?

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-cucumber-starter#18]
![image](https://user-images.githubusercontent.com/28752767/78232555-00fca680-7507-11ea-998f-215b07a76ae0.png)

{string} doesn't work with the step definition.

![image](https://user-images.githubusercontent.com/28752767/78233753-cbf15380-7508-11ea-9d2e-97c13fbbf1c2.png)

![image](https://user-images.githubusercontent.com/28752767/78233807-e1667d80-7508-11ea-9e9f-7783224bbf48.png)

**Comment by edricklacbayo** [comment]
Only this (.*) works

**Comment by edricklacbayo** [comment]
I still can't make it work.

**Comment by wakaleo** [comment]
You must use either cucumber expressions or reg exes in a given step definition - you cannot use both. Refer to the Cucumber docs for more details.

**Comment by edricklacbayo** [comment]
@wakaleo How do I know if I am using Regex or Cucumber Expression. I can't seem to make the cucumber expression work. Does it sense if I have already used a Regex or  I am just using the cucumber expression in a wrong format?

**Comment by kpkalyan** [comment]
I am also facing the same issue, 

@Given("{actor} open a browser and Web portal")
	public void webPortalLogin(Actor actor) {
		actor.wasAbleTo(GoTo.theWebPortalPage());
		actor.wasAbleTo(GoTo.clickLogin());
	}

@Then("{actor} should see the search results matched with search {searchText}")
	public void shouldSeeTheSearchResultsForSearchText(Actor actor, String searchText) {
		actor.attemptsTo(GoTo.VerifySearchResults(actor,searchText);
	}

@ParameterType(".*")
public Actor actor(String actorName) {
 return OnStage.theActorCalled(actorName);
}

Error:
Undefined Parameter type {actor}, please register parameter type {actor}
