### ISSUE TITLE
Cannot read beans details during compile

### ISSUE THREAD

**Issue by FrancisJoshuaCervantes** [serenity-bdd/serenity-cucumber-starter#21]
Hi @wakaleo ,  

Just want to ask because I am developing serenity-cucumber framework and it seems that is does not read any of the beans within the @ComponentScan({"dao", "services"}) package. In order to retrieve results from database. Especially it throws NullPointerException also, because it does not read environment variables. The framework is supposed to read the connection strings from a separate properties file. But unfortunately it does not read any of it during compile. 

Here is my config:
![image](https://user-images.githubusercontent.com/63582823/79123019-c24ed200-7dcb-11ea-9763-efdc6d518291.png)

My other question is, is their a way for cucumber to read those properties during compile and connect to the database? Thank you in advance.

Here is my TestRunner config:
![image](https://user-images.githubusercontent.com/63582823/79123192-2bcee080-7dcc-11ea-82c9-c2110960d8f8.png)

**Comment by wakaleo** [comment]
The EnvironmentVariables field is not managed by Spring, so you will need to get it directly from Guice if you are using it inside a Spring-managed object, e.g.
```
environmentVariables = Injectors.getInjector().getInstance(EnvironmentVariables.class);
```

**Comment by FrancisJoshuaCervantes** [comment]
> The EnvironmentVariables field is not managed by Spring, so you will need to get it directly from Guice if you are using it inside a Spring-managed object, e.g.
> 
> ```
> environmentVariables = Injectors.getInjector().getInstance(EnvironmentVariables.class);
> ```

Thank you for responding sir, I would like to ask another follow-up question, is there any atlernative for @ComponentScan? I would like to read the dao and services packages but turns out that @ComponentScan does not see any of the packages.

**Comment by FrancisJoshuaCervantes** [comment]
Already solved
