### ISSUE TITLE
Running by multiple tags

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-cucumber-starter#22]
I don't know if this is an issue or I am just using the wrong format. but supplying multiple tags to the command -Dcucumber.filter.tags doesn't work

For example:
-Dcucumber.filter.tags="@TCA-335 and @TCA-333"

**Comment by wakaleo** [comment]
The `cucumber.filter.tags` option will only work fully with version 2.2.2 of serenity-core.

**Comment by edricklacbayo** [comment]
@wakaleo upon checking, the latest version of serenity-core is 2.2.1. Does that mean that running by multiple tags is not yet supported? Do you have any idea on when version 2.2.2 will be released?

**Comment by edricklacbayo** [comment]
Hi @wakaleo I see that you've already released version 2.2.2 of serenity-core. Does that mean that I can now run by  multiple tags using -Dcucumber.filter.tags?

**Comment by edricklacbayo** [comment]
I have upgraded to version 2.2.2 of serenity-core and I tried running using these 2 formats but still no luck in running by multiple tags.

clean verify -Dcucumber.filter.tags="@TCA-335,@TCA-333'

clean verify -Dcucumber.filter.tags="@TCA-335 and @TCA-333"

Is my format wrong or Cucumber.filter.tags cannot run multiple tags yet?

**Comment by wakaleo** [comment]
Does it work with cucumber.options?

**Comment by edricklacbayo** [comment]
It says cucumber.options is deprecated. It suggests I use cucumber.filter.tags

**Comment by wakaleo** [comment]
Yes, but you can still use cucumber.options to check your tag syntax. Do you mean "@TCA-335 and @TCA-333" or "@TCA-335 **or** @TCA-333"

**Comment by wakaleo** [comment]
(See https://cucumber.io/docs/cucumber/api/#tags)

**Comment by edricklacbayo** [comment]
![image](https://user-images.githubusercontent.com/28752767/80180752-03e64500-8636-11ea-80a4-867b853d8f04.png)

IT returns this @wakaleo

**Comment by edricklacbayo** [comment]
![image](https://user-images.githubusercontent.com/28752767/80180810-1f515000-8636-11ea-9494-64c254b39d52.png)

This is my command

**Comment by wakaleo** [comment]
Here is how you would run two tags in Cucumber 5:
```
mvn clean verify -Dcucumber.filter.tags="@green or @blue"
```

But the output above suggests a problem with your test runner, not with the tag filtering.

**Comment by edricklacbayo** [comment]
Thanks, I got it to run. But why is it "or" though shouldn't it it be "and"?

**Comment by wakaleo** [comment]
“And” means run all the scenarios with both those tags

**Comment by edricklacbayo** [comment]
Now I get it. 

Another question, Does the "or" have a limit on the number of tags I provide?

I mean can I do this command?

-Dcucumber.filter.tags= @test1 or @test2 or @test3 or @test4

**Comment by wakaleo** [comment]
There is no limit

**Comment by edricklacbayo** [comment]
Thanks a lot @wakaleo
