### ISSUE TITLE
Junit Assert Compatibility

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-cucumber-starter#23]
Is cucumber not compatible with Assert of Junit?

Because when I use Assert, it results to 0 scenarios and 0 steps.

**Comment by wakaleo** [comment]
Cucumber works fine with any assertion library.

**Comment by edricklacbayo** [comment]
Yep, I just tested it, it does work. It was not working at the part where I assign @Given and @Then on one method. Just to confirm, this Jbehave thing I used to where I assign @Given and @Then on one method doesn't work on cucumber?

![image](https://user-images.githubusercontent.com/28752767/79707454-19cecf80-82ef-11ea-9afc-70abb3c05033.png)

**Comment by wakaleo** [comment]
You only need one annotation for this case, it will match both Given and The

**Comment by edricklacbayo** [comment]
Got it now. Thank you @wakaleo
