### ISSUE TITLE
Could not run Serenity+Cucumber+Java8+kotlin in parallel

### ISSUE THREAD

**Issue by pradeepbhardwaj007** [serenity-bdd/serenity-cucumber-starter#41]
While attempting to run cucumber scenarios in parallel I found that parallel=classes or methods has no control over parallelism. 
Below are some scenarios; I tried. Along with I am also attaching two projects in Kotlin.

[serenity-cucumberj8-starter.zip](https://github.com/serenity-bdd/serenity-cucumber-starter/files/5374458/serenity-cucumberj8-starter.zip)
[serenity-cucumber-starter.zip](https://github.com/serenity-bdd/serenity-cucumber-starter/files/5374459/serenity-cucumber-starter.zip)

Case 1: 
```xml
<parallel>methods</parallel>
<threadCount>2</threadCount>
<useUnlimitedThreads>false</useUnlimitedThreads>
```
Results of case 1: 
All 5 scenarios marked with tag '@runforestrun' starts running.   

Case 2: 
```xml
<parallel>classes</parallel>
<parallel>methods</parallel>
<threadCount>2</threadCount>
<useUnlimitedThreads>false</useUnlimitedThreads>
```
or 
```xml
<parallel>classes</parallel>
<parallel>methods</parallel>
<useUnlimitedThreads>true</useUnlimitedThreads>
```
Results of case 2: Scenarios executed sequentially; no parallelism achieved    
   
Case 3: 
```xml
<parallel>classes</parallel>
<threadCount>2</threadCount>
```
or 
```xml
<parallel>classes</parallel>
<useUnlimitedThreads>true</useUnlimitedThreads>
```
Results of case 3: Test cases are executed sequentially; no parallelism achieved

**Comment by wakaleo** [comment]
Parallel execution is managed by Cucumber, not by Serenity.

**Comment by ricardorlg-aval** [comment]
Cucumber in Junit doesn't support method level parallelism, and for classses it depends in how many runners u define.

**Comment by pradeepbhardwaj007** [comment]
Thank you very much for the above comments and this is working as mentioned. After providing runners i am able to achieve parallel execution. 
I am closing this issue.
