### ISSUE TITLE
Undefined Parameter type {actor}, Please register a Parameter Type for {actor}

### ISSUE THREAD

**Issue by kpkalyan** [serenity-bdd/serenity-cucumber-starter#47]
![image](https://user-images.githubusercontent.com/59632040/103114792-ededb180-4614-11eb-8055-48a96b6f5f5f.png)

import io.cucumber.java.ParameterType;
import net.serenitybdd.screenplay.Actor;
import net.serenitybdd.screenplay.actors.OnStage;

public class ParameterDefinitions {

	@ParameterType(".*")
	public Actor actor(String actorName) {
		return OnStage.theActorCalled(actorName);
	}

}

@Given("{actor} open(s) a browser and launch Web portal")
public void logsWebPortal(Actor actor) {
	actor.wasAbleTo(GoTo.theWebPortalLoginPage());
	actor.wasAbleTo(GoTo.clickLogin());
}

Error:
Undefined Parameter type {actor}, Please register a Parameter Type for {actor}

**Comment by xescuder** [comment]
Have you solved it?

**Comment by wakaleo** [comment]
Make sure the class with the @ParameterType annotation is in same package as your step definitions. This is a Cucumber configuration issue.

**Comment by jbaconsult** [comment]
> Make sure the class with the @ParameterType annotation is in same package as your step definitions. This is a Cucumber configuration issue.

This did not solve it for me. At least not in the Eclipse plugin.

**Comment by wakaleo** [comment]
Does it work from the command line?

**Comment by mjeffw** [comment]
I have this problem too, where while using the Cucumber plugin for Eclipse, the plugin flags this error. But the code actually works. The error is a nuisance (and I would love it if we can resolve it!) but not a show stopper.

**Comment by wakaleo** [comment]
Looks like Eclipse is not finding the @ParameterType method. If it works from the command line, it's most likely an Eclipse plugin bug, so probably best to raise an issue with them

**Comment by wakaleo** [comment]
The best solution is probably to use IntelliJ
