### ISSUE TITLE
Serenity System Properties and Configuration

### ISSUE THREAD

**Issue by punkratz312** [serenity-bdd/serenity-cucumber-starter#49]
I want to execute all features in one brower instance for debug reasons, or at least one after another.
By default serenity starts an browser instance for every feature file. This leads to problems. 

Thankfully some switches are already implemented like (restart.browser.each.scenario):

https://serenity-bdd.github.io/theserenitybook/latest/serenity-system-properties.html#_restart_browser_each_scenario

The documentations need to be updated and maybe the implementation too its not working at all. setting the switch to true and false does not change one thing.

Doc says default falue is false and it gets activated by false altho that sounds strange to me.

![image](https://user-images.githubusercontent.com/8830888/115857303-cfb28980-a42d-11eb-86e7-36b47d094dee.png)

I altho wanted to use serenity.use.unique.browser but it seems not to work or make and change eather:

Without headless i see browser instances for ever feature:

![image](https://user-images.githubusercontent.com/8830888/115857463-04bedc00-a42e-11eb-960f-8903fdcb2002.png)

heres my configuration:

![image](https://user-images.githubusercontent.com/8830888/115857572-23bd6e00-a42e-11eb-8899-fda15525460c.png)

**Comment by wakaleo** [comment]
Running all the features in a single browser is not possible because of the way Cucumber lifecycle events work.

**Comment by punkratz312** [comment]
What about at least one feature after another ?Putting them all in one file in fact does the trick maybe it’s slow but steady and it works. 

Thanks. I really appreciate the tool it’s really the best imho and gives a lot of pleasure.

**Comment by wakaleo** [comment]
`serenity.restart.browser.for.each = feature`

**Comment by punkratz312** [comment]
my bad im sorry i fixed the issue by removing multithreading:

![image](https://user-images.githubusercontent.com/8830888/115960289-ccdc9500-a510-11eb-85ee-bb102059c480.png)


now one feature runs after each other just how i expected it and know it was the behaviour back in thucydides days.



![image](https://user-images.githubusercontent.com/8830888/115960325-06ad9b80-a511-11eb-96b1-1b12fc9d416e.png)


maybe its questionable why its necessary to run all features at the same time by default.

thanks
