### ISSUE TITLE
Serenity Run using Cucumber Tags - Serenity Run Console indicates tests for ALL TAGS executed even when Single TAG is executed (Serenity Reports as expected)

### ISSUE THREAD

**Issue by TarahMo** [serenity-bdd/serenity-cucumber-starter#54]
Hi John @wakaleo 

I am noticing a strange behavior during build run-time within Serenity Console Run when running Serenity Tests using Cucumber Tags.

I have 6 Scenarios in the Feature File each with different Tags. When I run the project using Maven run configuration for a specific TAG e.g. for "GETSERVICES" TAG (for the highlighted scenario in the attached files), observations highlighted under 1) & 2) below.

1) When the build execution starts - I find it ambiguous looking at the Serenity Run Console as it indicates 6 TESTS Executed & 6 TESTS Passed. I have used log().all() in the REST Assured code which is logging the request & response and I can see ALL 6 API's have been executed.

2) Build is successful (Process finished with exit code 0 & BUILD SUCCESS) and when I look at "Serenity Summary Emailable Report" & "Index.HTML Report" -> as expected, I see ONLY 1 TEST (based on the TAG provided) executed & PASSED.

Therefore I am confused why Serenity Run Console indicates 6 TESTS Executed & 6 TESTS Passed & it actually does and I see GET & POST responses for ALL 6 API's in the console logs.

I have attached a few screen prints for the following files & have attached the Full Console Log as well.

Please can you advise what may be the reason for the above behavior?

Attached screen prints & logs for the following:

i) Serenity Run - Console Logs
ii) Serenity Run Logs
iii) Feature File
iv) Serenity Runner File
v) Maven Run Configuration
vi) Index.html Report
vii) serenity-summary.html (Serenity Summary Emailable Report)
viii) POM.XML Maven Failsafe Plugin
ix) POM.XML (full)

![Feature File](https://user-images.githubusercontent.com/85223433/123294076-258cd600-d532-11eb-9318-17e840a28184.JPG)

![Serenity Runner File](https://user-images.githubusercontent.com/85223433/123294117-2d4c7a80-d532-11eb-96ba-99eb7591f5ac.JPG)

[Serenity Run - Console Logs.txt](https://github.com/serenity-bdd/serenity-rest-starter/files/6710558/Serenity.Run.-.Console.Logs.txt)

[POM XML.txt](https://github.com/serenity-bdd/serenity-rest-starter/files/6710682/POM.XML.txt)

![Serenity Run Logs](https://user-images.githubusercontent.com/85223433/123294183-3d645a00-d532-11eb-9097-75085cd12648.JPG)

![Serenity Summary Emailable Report](https://user-images.githubusercontent.com/85223433/123296856-a2b94a80-d534-11eb-8fff-7ae86cb419a2.JPG)

![Index HTML Report](https://user-images.githubusercontent.com/85223433/123296898-ad73df80-d534-11eb-86cb-61be37b107c6.JPG)

![Maven Run Configuration](https://user-images.githubusercontent.com/85223433/123297270-0f344980-d535-11eb-8600-40385a473c68.JPG)

![POM XML Maven Failsafe Plugin](https://user-images.githubusercontent.com/85223433/123294293-5836ce80-d532-11eb-977b-6e2ef6b3216f.JPG)

**Comment by wakaleo** [comment]
Looks like a bug.

**Comment by TarahMo** [comment]
Hi John - do you mean a bug in serenity using cucumber with tags? I have spent quite a lot of time looking at the pom & my code & the serenity documentation though everything looks alright to me. I have also added 'serenity.exclude.unrelated.requirements.of.type = capabilities' in serenity.conf but that didn't resolve the issue.

Do you mind taking a quick look at the screenshots I attached above if you see anything that's not right?

**Comment by TarahMo** [comment]
Hi John @wakaleo 
- do you mean a bug in serenity using cucumber with tags? I have spent quite a lot of time looking at the pom & my code & the serenity documentation though everything looks alright to me. I have also added 'serenity.exclude.unrelated.requirements.of.type = capabilities' under serenity.conf but that didn't resolve the issue.

Do you mind taking a quick look at the screenshots I attached above if you see anything that's not right?

**Comment by wakaleo** [comment]
Probably a bug in the Serenity code.

**Comment by TarahMo** [comment]
Can we probably clock/register it somewhere?

**Comment by TarahMo** [comment]
@wakaleo - Can I provide a project that reproduces this behaviour?

**Comment by wakaleo** [comment]
Yes, but raise this issue on https://github.com/serenity-bdd/serenity-core rather than here.

**Comment by TarahMo** [comment]
Sure John. I have created the above issue under serenity-core and shared the project details. Closing this issue here.
