### ISSUE TITLE
JUnit Run Viewer does not show Given When Then hierarchy 

### ISSUE THREAD

**Issue by pradeep-baskaran** [serenity-bdd/serenity-cucumber-starter#6]
Old version does show the hierarchy. This is very good during debugging.

        <serenity.version>1.5.11</serenity.version>
        <serenity.maven.version>1.5.3</serenity.maven.version>
        <serenity.cucumber.version>1.5.4</serenity.cucumber.version>

![old version](https://user-images.githubusercontent.com/41713832/43238588-54ea5a8a-90ac-11e8-8443-c0c09da39f91.jpg)

Newer version does not show the hierarchy.
![new version](https://user-images.githubusercontent.com/41713832/43238613-6df81ea4-90ac-11e8-82e7-e6d8d7cb28fc.jpg)

**Comment by wakaleo** [comment]
This is related to the Cucumber IntelliJ runner, not Serenity.

**Comment by pradeep-baskaran** [comment]
Even Eclipse Runner has the same problem. Is there a solution for this?

**Comment by wakaleo** [comment]
You should ask on the cucumber-JVM groups, as Serenity simply extends the standard Cucumber runner

**Comment by wakaleo** [comment]
Just checked - this is a Cucumber bug that also occurs when you use the normal Cucumber runner. I would advise raising a defect with the Cucumber team.
