### ISSUE TITLE
IntelliJ Weird Intellisense Bug With `net.serenitybdd.screenplay.ensure.Ensure`

### ISSUE THREAD

**Issue by cjekal** [serenity-bdd/serenity-cucumber-starter#68]
When trying to load this sample project in IntelliJ 2020.2, the syntax error highlighter shows that this import statement is incorrect:

`import net.serenitybdd.screenplay.ensure.Ensure;`

I'm not sure if it's b/c `serenity-ensure` is written in Kotlin or some other issue, but any pointers would be super helpful.

**Comment by wakaleo** [comment]
This is an IntelliJ bug - I believe it is fixed in more recent versions of IntelliJ.

**Comment by cjekal** [comment]
Thanks for the clarification! Does it have anything to do with serenity-ensure being written in Kotlin?

**Comment by wakaleo** [comment]
Yes, it seems to be a bug in the Intellij autocomplete with Kotlin code.
