### ISSUE TITLE
Chrome browser zoomed more than 100% in serenity 3.2.1 

### ISSUE THREAD

**Issue by atulinforma** [serenity-bdd/serenity-cucumber-starter#74]
I have recently updated the serenity version from 2.3.8 to 3.2.1. After fixing all the dependency, the scripts are failing  in linux machine for 3.2.1 and the chrome browser is zoomed more than 100%, same code works fine in 2.3.8 version

**Comment by wakaleo** [comment]
Version 3.2.1 uses Selenium 4 so there may be different options for the chromedriver - this doesn't look like something related to the Serenity library as such though.

**Comment by wakaleo** [comment]
Try experimenting with setting those options explicitly via the chrome options

**Comment by atulinforma** [comment]
Thanks for the response, will try.
