### ISSUE TITLE
index.html is not generating at the end report

### ISSUE THREAD

**Issue by manjugb** [serenity-bdd/serenity-cucumber-starter#8]
I followed pom.xml to create my scripts 
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features = {"src/test/resources/youTube/"}, glue = {"stepdefinitons"},format={"pretty"})
public class RunCukesTest {

 }

here is my pom.xml
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.0.23</serenity.version>
        <serenity.maven.version>2.0.23</serenity.maven.version>
        <serenity.cucumber.version>1.9.20</serenity.cucumber.version>
        <encoding>UTF-8</encoding>
        <tags></tags>
        <parallel.tests>4</parallel.tests>
        <webdriver.base.url></webdriver.base.url>
    </properties>

    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>http://jcenter.bintray.com</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.13</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-webdriver</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/*TestSuite.java</include>
                        <include>**/When*.java</include>
                    </includes>
                    <systemPropertyVariables>
                        <webdriver.base.url>${webdriver.base.url}</webdriver.base.url>
                    </systemPropertyVariables>
                    <parallel>classes</parallel>
                    <threadCount>${parallel.tests}</threadCount>
                    <forkCount>${parallel.tests}</forkCount>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <configuration>
                  <tags>${tags}</tags>
                </configuration>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
</build>

**Comment by wakaleo** [comment]
Did you run mvn verify?

**Comment by manjugb** [comment]
yes, I ran through mvn and i couldnt seen index.html in the serenity folder which generated

**Comment by wakaleo** [comment]
“Mvn verify” should generate the reports in target/site/serenity

**Comment by manjugb** [comment]
I tried with below
mvn clean verify
mvn verify
mvn clean test
None of them index.html were not generated

**Comment by anastasiia12** [comment]
I have the same issue with versions:

   <serenity.version>2.0.24</serenity-rest-assured>
   <serenity.maven.version>2.0.24</serenity.maven.version>
   <serenity.cucumber.version>1.9.21</serenity.cucumber.version>

Execution for the **index.html** doesn't work in pom.  It works only when you execute in console: **mvn serenity:aggregate**

**Comment by manjugb** [comment]
I will try that command

**Comment by manjugb** [comment]
Let me try that command

**Comment by manjugb** [comment]
Now it worked using mvn serenity:aggregate
Thank You anastasiia12

**Comment by wakaleo** [comment]
I haven’t been able to reproduce this at all - mvn clean verify on a clean copy of the repo should generate the full reports.

**Comment by manjugb** [comment]
finally it creates using mvn clean verify after i clean .m2 repository

**Comment by PrasadNutalapati** [comment]
I started off with the latest **serenity-cucumber-starter** template project using both Eclipse and IntelliJ, and JDK 1.8_127. The same situation is happening with my testing also. The generation of index.html is random. Some time it gets generated when I run the **Runner** file, some times as **mvn clean verify/install**.

Again major problem is suddenly the IDE especially intelliJ shows one of the pageObject class as not able to resolve almost all the framework classes and their methods like 

- PageObject
- WebElementFacade
- FindBy() method etc

After following the IDE suggestion that to attach serenity-core as dependency (which is already present in the pom file), the classes and methods gets resolved. But nevertheless, the running of the project gets stopped showing/citing dependency problems from pom.xml file. I never touch pom.xml file after initial project import. Why this **flakiness** in the framework ? How to resolve it permanently. 

I happen to use the Serenity in 2017-2018 successfully. I never come across this type of problem, except logical and programmatic issues which are my responsibility !
**_What is the most stable version starter project in the available options ? Please help me by naming that. I will follow only that at least I can be moving ahead with my work, with out being bogged down by the framework issues._** 

To help improve the framework, I am not that good with the framework in the first place, sorry ! 
.,

**Comment by wakaleo** [comment]
This is an environment and/or IDE issue, it is not related to Serenity BDD or the starter project. Reports are generated by the maven report plugin, not after each individual test (see https://github.com/serenity-bdd/serenity-cucumber-starter/blob/master/README.md#generating-the-reports). 

Missing dependencies are an environment or IDE issue. If it builds on the command line, it is an IDE issue, otherwise it is probably a Maven repository issue. If you need help with setting up your development environment, you can post your question on Gitter (https://gitter.im/serenity-bdd/serenity-core) or ask the Maven community (https://maven.apache.org/users/getting-help.html). If you are having issues with IntelliJ, then the IntelliJ folk are the best people to ask for help.

**Comment by satyayalamanchi** [comment]
I am using **gradle** with spring boot. I am getting same issue. Aggregation task not generating index.html. 
Sometimes the report looks good but other times index page will be either blank or show last execution data.
After getting empty report, I tried running **aggregate** task alone. 
Surprisingly, run in IntelliJ is giving same empty result but debug is giving the correct expected result
I using the command - **clean test aggregate reports**. 
Please let me know if I am missing anything.


```
buildscript {
	repositories {
		mavenLocal()
		jcenter()
	}
	dependencies {
		classpath("net.serenity-bdd:serenity-gradle-plugin:2.3.4")
		classpath("net.serenity-bdd:serenity-single-page-report:2.3.4")
	}
}

plugins {
	id 'org.springframework.boot' version '2.3.4.RELEASE'
	id 'io.spring.dependency-management' version '1.0.10.RELEASE'
	id 'java'
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

repositories {
	mavenLocal()
	jcenter()
}

group = 'com.test.qa'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations.all {
	resolutionStrategy {
		force "io.cucumber:cucumber-core:6.6.0"
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
	compile group: 'mysql', name: 'mysql-connector-java', version: '8.0.20'

	testCompile group: 'io.cucumber', name: 'cucumber-junit', version: '6.6.0'

	compile "net.serenity-bdd:serenity-core:2.3.4",
			"net.serenity-bdd:serenity-cucumber6:2.3.4"
	testCompile group: 'net.serenity-bdd', name: 'serenity-spring', version: '2.3.4'
	testCompile group: 'net.serenity-bdd', name: 'serenity-model', version: '2.3.4'
	testCompile group: 'net.serenity-bdd', name: 'serenity-reports', version: '2.3.4'

	compile group: 'org.assertj', name: 'assertj-core', version: '3.16.1'

	compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.0'
	compile group: 'commons-httpclient', name: 'commons-httpclient', version: '3.1'

	compile group: 'org.apache.poi', name: 'poi', version: '4.1.0'
	compile group: 'org.apache.poi', name: 'poi-ooxml', version: '4.1.0'

	compile group: 'com.github.javafaker', name: 'javafaker', version: '1.0.2'
}

serenity {
	reports = ["single-page-html"]
}

test {
	systemProperty "cucumber.filter.tags", System.getProperty('cucumber.filter.tags')
}

test.ignoreFailures=true
test.finalizedBy(aggregate, reports)
```

![image](https://user-images.githubusercontent.com/8208073/102749459-ad96e680-4329-11eb-9ed2-8a4f799774c7.png)

**Comment by wakaleo** [comment]
Try deleting the serenity-resources file in the target/site/serenity directory.

**Comment by satyayalamanchi** [comment]
Thanks for the response.
target directory is getting deleted while clean task and created at the time of test task.
serenity-resources file gets generated after the test execution is done. 
Please help me understand how the deletion of serenity-resources file would resolve the issue with aggregate.
Is there anything that I can to do before test execution to get aggregated report?

**Comment by satyayalamanchi** [comment]
I figured out a work around. Executing aggregate task in debug mode is resolving the issue.

**Comment by sudhir-kunchakuri** [comment]
HI @satyayalamanchi 
I am using Intellij tool and Gradle build for my automation project and even i face the same issue that sometimes index report is blank.
Could you please tell me what exactly you did to overcome this issue..

**Comment by satyayalamanchi** [comment]
After getting a blank index report, in run configurations, I have only aggregate task and hit the debug. This is generating the report for the last executed test.

**Comment by sudhir-kunchakuri** [comment]
![image](https://user-images.githubusercontent.com/70365103/103080658-49f80c00-45fc-11eb-9d94-d4507f67ff90.png)
@satyayalamanchi ,
i have attached the screenshot of options visible after clicking on Run menu item.. can u please tell me what exactly i need to do now..?

**Comment by satyayalamanchi** [comment]
Sorry for the late response.
Create a run configuration with aggregate task

![image](https://user-images.githubusercontent.com/8208073/103333165-8085ba80-4a32-11eb-8ac1-340e85c600ba.png)

Then select the run configuration and click on debug

![image](https://user-images.githubusercontent.com/8208073/103333212-bb87ee00-4a32-11eb-98a1-9a24a2f93ca9.png)

Hope this helps.

**Comment by sudhir-kunchakuri** [comment]
Thanks @satyayalamanchi ..it worked..
please let me know when u know the permanent solution for it.. so that report will get auto generated for every execution.
